/*
 * check_netscaler_gateway v2.0 - Icinga 2 CheckCommand Definition
 * https://github.com/slauger/check_netscaler_gateway
 */

object CheckCommand "netscaler_gateway" {
  import "plugin-check-command"
  command = [ PluginDir + "/check_netscaler_gateway" ]
  arguments = {
    "-H" = {
      value = "$netscaler_address$"
      description = "Hostname of the NetScaler Gateway vServer"
    }
    "-u" = {
      value = "$netscaler_user$"
      description = "Username for the login simulation"
    }
    "-p" = {
      value = "$netscaler_password$"
      description = "Password for the login username"
    }
    "-S" = {
      value = "$netscaler_storename$"
      description = "Name of the store in StoreFront"
    }
    "-w" = {
      value = "$netscaler_warning$"
      description = "Minimum number of expected applications before WARNING"
    }
    "-c" = {
      value = "$netscaler_critical$"
      description = "Minimum number of expected applications before CRITICAL"
    }
    "-t" = {
      value = "$netscaler_timeout$"
      description = "Request timeout in seconds"
    }
    "--auth-mode" = {
      value = "$netscaler_auth_mode$"
      description = "Authentication flow: auto, classic or nfactor"
    }
    "--verify" = {
      set_if = "$netscaler_verify$"
      description = "Verify TLS certificates"
    }
    "-v" = {
      set_if = "$netscaler_verbose$"
      description = "Verbose output"
    }
  }

  vars.netscaler_address = "$address$"
}
